/**
 *
 * @param Theme can be spread like {Colors, NavigationColors, Gutters, Layout, Common, ...args}
 * @return {*}
 */
export default function () {
  return {
    logo: require("@/assets/images/Logo_Menu.png"),
    firstLogo: require("@/assets/images/HajdeLogo_White.png"),
    background: require("@/assets/images/Login.png"),
    firstBackground: require("@/assets/images/FirstBackground.png"),
    loginBackground: require("@/assets/images/LoginBackground.png"),
    authBackground: require("@/assets/images/Register.png"),
    loginButton: require("@/assets/images/Confirm_logo_Default.png"),
    hajdeStamp: require("@/assets/images/Hajde_Stamp_White.png"),
    backButton: require("@/assets/images/BackButton.png"),
    dropDownIcon: require("@/assets/images/Dropdown_icon.png"),
    cartIcon: require("@/assets/images/Shporta_icon.png"),
    superMarket: require("@/assets/images/SuperMarket.png"),
    restaurant: require("@/assets/images/Restaurant.png"),
    turbo: require("@/assets/images/Turbo.png"),
    drink: require("@/assets/images/Drink.png"),
    farmacy: require("@/assets/images/Farmacy.png"),
    flowers: require("@/assets/images/Flowers.png"),
    lunchPack: require("@/assets/images/IconSetLunchPack.png"),
    petCare: require("@/assets/images/PetCare.png"),
    fitness: require("@/assets/images/Fitness.png"),
    homeTopBanner: require("@/assets/images/HomeTopBanner.png"),
    banner1: require("@/assets/bannerV1.png"),
    banner2: require("@/assets/images/banner2.png"),
    banner3: require("@/assets/images/banner3.png"),
    orderIcon: require("@/assets/images/OrderIcon.png"),
    profileIcon: require("@/assets/images/ProfileIcon.png"),
    birdStampIcon: require("@/assets/images/BirdStampIcon.png"),
    favoriteIcon: require("@/assets/images/FavoriteIcon.png"),
    shportaIcon: require("@/assets/images/ShportaIcon.png"),
    orderIconActive: require("@/assets/images/OrderIconActive.png"),
    profileIconActive: require("@/assets/images/ProfileIconActive.png"),
    favoriteIconActive: require("@/assets/images/FavoriteIconActive.png"),
    shportaIconActive: require("@/assets/images/ShportaIconActive.png"),
    superMarketCover: require("@/assets/images/SupermarketCover.png"),
    restaurantCover: require("@/assets/images/RestaurantCover.png"),
    categoriesIcon: require("@/assets/images/CategoriesIcon.png"),
    riderIcon: require("@/assets/images/RiderIcon.png"),
    clockIcon: require("@/assets/images/ClockIcon.png"),
    clockRedIcon: require("@/assets/images/ClockRedIcon.png"),
    stampOriginalIcon: require("@/assets/images/stamp_original.png"),
    addressMap: require("@/assets/images/addressMap.png"),
    imgLocation: require("@/assets/images/lokacioni.png"),
    imagDate: require("@/assets/images/ora.png"),
    imgMotor: require("@/assets/images/motorri.png"),
    imgOffer: require("@/assets/images/oferta.png"),
    imgCross: require("@/assets/cross.png"),
    iconClear: require("@/assets/icons/clearIcon.png"),
    iconEdit: require("@/assets/icons/editIcon.png"),
    iconEditAddress: require("@/assets/icons/editAddressIcon.png"),
    megaphone: require("@/assets/images/megaphone.png"),
    megaphoneFlipped: require("@/assets/images/megaphone-flipped.png"),
    amChef: require("@/assets/animations/1-Chef.json"),
    amSpaghetti: require("@/assets/animations/2-Spaghetti.json"),
    amMenu: require("@/assets/animations/3-Menu.json"),
    amFastFood: require("@/assets/animations/4-FastFood.json"),
    amSushiBar: require("@/assets/animations/11-SushiBar.json"),
    amRoastedChicken: require("@/assets/animations/12-RoastedChicken.json"),
    amBirdFlying: require("@/assets/animations/BirdFlying.json"),
    amClocheLoading: require("@/assets/animations/ClocheLoading.json"),
    amCourier: require("@/assets/animations/Courier.json"),
    amCourier_v2: require("@/assets/animations/Courier_v2.json"),
    amFlyingHajde: require("@/assets/animations/FlyingHajde.json"),
    amGroceriesiFood: require("@/assets/animations/GroceriesiFood.json"),
    amSearchBar: require("@/assets/animations/SearchBar.json"),
    amHiWink: require("@/assets/animations/HiWink.json"),
    amIsometricMotorcycleDelivery: require("@/assets/animations/IsometricMotorcycleDelivery.json"),
    amLoadingBar1: require("@/assets/animations/LoadingBar1.json"),
    amLoadingFoodPrepared: require("@/assets/animations/LoadingFoodPrepared.json"),
    amShoppingCart: require("@/assets/animations/ShoppingCart.json"),
    amSignalLoading: require("@/assets/animations/SignalLoading.json"),
    amIntro: require("@/assets/animations/Intro.json"),
    amFlying: require("@/assets/animations/1- Flying Hajde.json"),
    amWink: require("@/assets/animations/2- Hi Wink.json"),
    amDone: require("@/assets/animations/Done.json"),
    amCanceled: require("@/assets/animations/Canceled.json"),
  };
}
