require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

platform :ios, '12.0'

require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

project 'hajdeapp',
  'Debug Dev' => :debug,
  'Release Dev' => :release,
  'Debug Staging' => :debug,
  'Release Staging' => :release,
  'Debug Production' => :debug,
  'Release Production' => :release

target 'hajdeapp' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes'
  )
  target 'hajdeappStaging' do
  end
  target 'hajdeappDev' do
  end

  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  # end

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

  post_install do |installer|
    react_native_post_install(installer)

    # Map enviroment configuration per scheme
    ENVFILES = {
      'Debug Dev' => '$(PODS_ROOT)/../../.env.development',
      'Release Dev' => '$(PODS_ROOT)/../../.env.development',
      'Debug Staging' => '$(PODS_ROOT)/../../.env.staging',
      'Release Staging' => '$(PODS_ROOT)/../../.env.staging',
      'Debug Production' => '$(PODS_ROOT)/../../.env',
      'Release Production' => '$(PODS_ROOT)/../../.env',
    }

    # Workaround `Cycle inside FBReactNativeSpec` error for react-native 0.64
    # Reference: https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-812543933
    installer.pods_project.targets.each do |target|
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          # Env file setup. This adds the env config file mapped above in ENVFILE
          # variable to the ENVFILE buildsetting for react-native-config
          if target.name == 'react-native-config'
            config.build_settings['ENVFILE'] = ENVFILES[config.name]
          end

          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end

end
