import { StyleSheet } from "react-native";
export default function ({ Colors, Layout, Gutters }) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.white,
    },
    infoContainer: {
      alignItems: "flex-start",

      width: "100%",
      alignSelf: "center",
      borderTopLeftRadius: 50,
      borderTopRightRadius: 50,
      position: "absolute",
      top: "15%",
      bottom: 0,
      backgroundColor: Colors.white,
    },
    infoInnerContainer: {
      flex: 1,
      alignSelf: "center",
      width: "90%",
    },
    restoranTitleContainer: {
      backgroundColor: Colors.primary,
      width: "100%",
      borderTopLeftRadius: 50,
      borderTopRightRadius: 50,
    },
    restoranTitle: {
      fontSize: 25,
      color: Colors.white,
      fontFamily: "Avenire-Bold",
      width: "85%",
      paddingTop: 15,
      paddingBottom: 5,
      fontWeight: "bold",
    },
    informations: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 4,
    },
    subTitle: {
      fontSize: 10,
      paddingLeft: 5,
      fontFamily: "Montserrat-Regular",
    },
    timeContainer: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 2,
      marginLeft: 0,
    },
    time: { fontSize: 15, paddingLeft: 5 },
    date: { fontSize: 10, paddingLeft: 5, fontWeight: "bold" },
    currency: {
      fontSize: 10,
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 5,
      marginLeft: 5,
    },
    img: {
      flex: 0.4,
      resizeMode: "center",
      width: "100%",
    },
    backButton: {
      position: "absolute",
      left: 20,
      top: 25,
    },
    categoriesContainer: {
      width: "100%",
      flexDirection: "row",
      paddingTop: 10,
      backgroundColor: Colors.white,
      alignSelf: "center",
      overflow: "hidden",
      paddingBottom: 10,
    },
    quantityContainer: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      paddingLeft: 15,
      paddingBottom: 5,
    },
    number: {
      paddingHorizontal: 10,
    },
    containerInfo: {
      display: "flex",
      flexDirection: "row",
    },
    cardImg: {
      height: 60,
      width: 60,
    },
    containerCardOld: {
      width: "100%",
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-end",
      alignSelf: "center",
      marginBottom: 10,
      marginTop: 10,
      backgroundColor: Colors.primary,
      shadowColor: Colors.black,
      shadowOffset: {
        width: 4,
        height: 8,
      },
      shadowOpacity: 0.1,
      shadowRadius: 5,
      elevation: 5,
      padding: 10,
      borderRadius: 10,
      borderColor: Colors.primary,
      borderWidth: 1,
    },
    containerCard: {
      width: "100%",
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-end",
      alignSelf: "center",
      marginBottom: 0,
      marginTop: 10,
    },
    nameContainer: {
      paddingLeft: 3,
      width: 210,
    },
    name: {
      marginTop: 10,
      fontSize: 16,
      fontFamily: "Montserrat-Bold",
      color: "#303030",
      marginBottom: 10,
    },
    description: {
      fontSize: 10,
      fontFamily: "Montserrat-Regular",
      color: "#303030",
    },
    bottomCardInfo: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      paddingTop: 15,
    },
    addProductsContainer: { flexDirection: "row", alignItems: "center" },
    price: {
      fontSize: 16,
      fontFamily: "Montserrat-SemiBold",
      color: "#111111",
      paddingTop: 22,
      paddingBottom: 10,
    },
    ofertaImage: {
      height: 100,
      width: 100,
      justifyContent: "flex-start",
      alignItems: "center",
      textAlign: "center",
      paddingBottom: 10,
    },
    bannerTitleBottomTitle: {
      color: Colors.white,
      fontSize: 16,
    },
    ofertPrice: {
      fontSize: 18,
      fontWeight: "bold",
      color: Colors.white,
    },
    bottomContainer: {
      display: "flex",
      flexDirection: "row",
      alignSelf: "center",
      backgroundColor: Colors.primary,
      width: "80%",
      borderTopRightRadius: 30,
      borderTopLeftRadius: 30,
      justifyContent: "space-around",
      alignItems: "center",
      paddingVertical: 5,
    },
    shportaImg: {
      height: 30,
      width: 30,
      resizeMode: "contain",
    },
    coreImage: {
      height: 140,
      width: 130,
      resizeMode: "contain",
      borderRadius: 8,
    },
    button: {
      height: 27,
      width: 27,
      borderRadius: 27,
      backgroundColor: Colors.grayCode70,
      justifyContent: "center",
      alignItems: "center",
    },
    searchContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderRadius: 10,
      borderWidth: 1,
      paddingLeft: 10,
      paddingVertical: 10,
      backgroundColor: Colors.white,
      opacity: 0.9,
      borderColor: "#a4a4a490",
    },
    headerInfoContainer: { height: 258, flexDirection: "row" },
    headerInfoBackButton: { left: 5, top: 90 },
    headerInfo: { backgroundColor: Colors.white, borderRadius: 20 },
    headerInfoImage: { width: 75, height: 55, borderRadius: 5 },
    deliveryNameContainer: {
      backgroundColor: Colors.white,
      borderBottomWidth: 0,
      borderTopStartRadius: 100,
      borderTopEndRadius: 100,
      height: 56,
      justifyContent: "center",
      alignItems: "center",
    },
    deliveryName: {
      color: Colors.header,
      fontSize: 29,
      fontFamily: "Montserrat-Medium",
    },
    offersContainer: {
      ...Layout.fullWidth,
      ...Layout.rowHCenter,
      ...Layout.justifyContentBetween,
      ...Gutters.normalHPadding,
      backgroundColor: Colors.primary,
      height: 44,
      ...Gutters.smallTMargin,
    },
    offerImage: { width: 28, height: 29 },
    offerText: {
      color: Colors.white,
      fontSize: 16,
      fontFamily: "Montserrat-SemiBold",
    },
    goToCart: { color: Colors.primary, fontSize: 20, fontWeight: "bold" },
    total: { color: Colors.primary, fontSize: 18 },
    offersAndSubcategories: {
      paddingHorizontal: 20,
      borderBottomWidth: 1,
      borderBottomColor: "#e4e4e4",
    },
    cardOldContainer: {
      borderRightWidth: 2,
      borderColor: Colors.primary,
      paddingRight: 5,
      justifyContent: "center",
      alignItems: "center",
    },
  });
}
